spring.application.name=backend

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/my_database
spring.datasource.username=admin
spring.datasource.password=postgres_password_123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurtion

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration

jwt.secret=shauryasharmaisno1coderinthewholeworldhahahahahahaha
jwt.acess-token-expiration=900000
jwt.refresh-token-expiration=2592000000

# OAuth2-Google

spring.security.oauth2.client.registration.google.client-id=GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile

# AWS S3 Media

aws.s3.bucket=jan_connect_media
aws.s3.region=ap-south-1
aws.s3.acess-key=ACCESS_KEY
aws.s3.secret-key=SECRET_KEY
aws.s3.cdn-base-url=https://cdn.janconnect.app

# Guest Session Configuration

jwt.guest-token-expiration=86400000

app.pagination.default-size=15

# Swagger Configuration

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html



